apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: Exec
metadata:
  name: example-exec-try
spec:
  deletionPolicy: Orphan
  forProvider:
    databaseRef:
      name: example-db
    exec: |
      CREATE TABLE acdeerefesdxggij (
          PersonID int,
          LastName varchar(255),
          FirstName varchar(255),
          Address varchar(255),
          City varchar(255)
      );
